/**
 * @author	Chris Marshall
 * @see		License at http://razor-cloud.com/razor/License.html
 * @version	4.0.0
 */
package net.cbtltd.shared;

public enum Method {
	BALANCE, QUANTITY, MONTHCHART, YEARCHART, ENTITYTYPE,
	ATTRIBUTE, ARCHIVE, CREATE, DELETE, EXISTS, ITEMTABLE, NAME, READ, UPDATE, WRITE,
	AGENTCREATE, AGENTSCREATE, AGENTDELETE, AGENTSDELETE, ORGANIZATIONCREATE,
	COUNTRYNAME, CURRENCYNAME, DEPRECIATIONNAME, NEARBYNAME, REGIONNAME,
	MARKETREGION, MARKETLOCATION, MARKETREAD, POSITION,
	AUTOLOGIN, LOGIN, LOGOUT, PASSWORDCREATE, PASSWORDUPDATE};
